apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: slo-ui-ingress
  namespace: slo-engine
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - slo.internal.company.com
      secretName: slo-ui-tls
  rules:
    - host: slo.internal.company.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: slo-ui-service
                port:
                  number: 80
